### ISSUE TITLE
Error: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by jackwener** [Renato66/auto-label#33]
Run action failed: 

```
*** running renato66/auto-label version 2.1.2 ***
Getting repository labels...
Repository labels found: 7
Reading labels in issue...
{ error: 'bug',
  'need fix': 'bug',
  'not working': 'bug',
  upgrade: 'enhancement',
  help: 'question' }
Error: Cannot read property 'replace' of null
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at Object.getIssueLabels (/lib/functions.js:66:39)
    at /lib/main.js:37:45
    at Generator.next (<anonymous>)
    at fulfilled (/lib/main.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by jackwener** [comment]
It's due to the github disable write access `fork repo` branch into the office repo

**Comment by carlaares** [comment]
@jackwener 

> It's due to the github disable write access `fork repo` branch into the office repo

Hello! How can we fix it? Thanks in advance.
