### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nikskiz** [Renato66/auto-label#52]
Getting the following error
```
*** running renato66/auto-label version 2.1.2 ***
Getting repository labels...
Repository labels found: 15
Reading labels in issue...
Error: Cannot read properties of null (reading 'replace')
/lib/functions.js:66
        const noCommentaryBody = body.replace(/\<!--(.|\n)*?-->/g, '');
                                      ^

TypeError: Cannot read properties of null (reading 'replace')
    at Object.getIssueLabels (/lib/functions.js:66:39)
    at /lib/main.js:37:45
    at Generator.next (<anonymous>)
    at fulfilled (/lib/main.js:5:5[8] 
```

**Comment by dantebarba** [comment]
Same problem, it's simple it happens when you create an issue without a body. When the auto-label workflow runs and finds an issue without a body it fails with that message.

**Comment by dantebarba** [comment]
https://github.com/Renato66/auto-label/issues/35
